### ISSUE TITLE
Identity/signing

### ISSUE THREAD

**Issue by parkan** [mediachain/L-SPACE#13]
(see below)

**Comment by parkan** [comment]
@yusefnapora my thinking is that at this point this is literally just a gitignored directory with some pem files and a data structure with `institution_id:public_key:fingerprint` or similar.

Feel free to drop any thoughts you have in here at end of day -- let's really try not overthink this part for now :smile:

**Comment by yusefnapora** [comment]
That sounds fine for the short term... right now I'm ignoring the issue of where / how to store the keys until we can get some basic signing working in e.g. a unit test.  

I figure for that we should be able to generate keypairs in memory and at least verify that e.g. changing the content invalidates the signature check, etc...

**Comment by parkan** [comment]
sgtm!

**Comment by yusefnapora** [comment]
Wanted to put down some of my thoughts about hashing / signing objects, and hopefully make a workable plan for implementing.

I'm mostly focused on hashing at the moment, since it's a prerequisite for signing.  The big question is: what exactly are we hashing?

So far, we have the ability to hash a serialized CBOR representation of our vertex case classes by having them extend a `Hashable` trait and excluding some properties from the serialized output.  At the moment, just the `id` field is excluded, since it's dependent on internal DB state, and we want the hash to be consistent across machines / subgraphs, etc.

One option is to require all of our vertices to store their hash as a property on the vertex.  That property would have to be ignored when generating the hash, of course.  This would be done at ingestion time when we insert the vertex into the graph.  Orient constraints would be helpful here to mark that field as mandatory and read-only.

If all vertices have a `contentHash` property, then edges can store the hashes of the incoming and outgoing vertices as edge properties.  This would make edge classes usefully `Hashable` as well, since you'd be able to identify the source and target nodes by their hash instead of an instance-specific `id`.

The other possibility that seems workable to me is to embed the outgoing edges in the serialized representation of the vertex before hashing.  This would be similar to the GraphSON output, which looks something like:

```json
{"id": "#1:0",
 "label": "PhotoBlob",
 "properties": {"..."},
 "outE": {
   "authored_by": [
     {
        "id": "#an-edge-id",
        "inV": "#a-vertex-id"
     }
   ]
 }
```

For this to work without using `id`, you'd have to replace `id` with `contentHash` for the vertices you're pointing to.

The advantage of the first approach is that you can sign individual edges, so it's more granular than signing a vertex with all of its outgoing edges embedded.

The second approach maps more directly onto the IPLD model, which has no independent "edges", although you can store properties on a `@link` object.

As far as implementation goes, the first approach seems simpler to implement, because we can serialize and hash a vertex case class without needing its edges.  I'm inclined to go that route.  

I don't think the similarity to the IPLD model is worth much at this stage, since we're going to need a pretty involved transformation step for that anyway when we actually get there.

**Comment by parkan** [comment]
Superseded, largely
